In [2]:
import pandas as pd

In [3]:
data = {
    "Hours_Studied": [4, 6, 5, 7, 3],
    "Attendance" : [80, 90, 85, 95, 70],
    "Assignment_Score": [75, 88, 82, 91, 65],
    "Sleep_Hours" : [6, 7, 5, None, 4],
    "Final_Grade": ["B", "A", "B", "A", "C"]
}

data

{'Hours_Studied': [4, 6, 5, 7, 3],
 'Attendance': [80, 90, 85, 95, 70],
 'Assignment_Score': [75, 88, 82, 91, 65],
 'Sleep_Hours': [6, 7, 5, None, 4],
 'Final_Grade': ['B', 'A', 'B', 'A', 'C']}

In [4]:
df = pd.DataFrame(data)
df

   Hours_Studied  Attendance  Assignment_Score  Sleep_Hours Final_Grade
0              4          80                75          6.0           B
1              6          90                88          7.0           A
2              5          85                82          5.0           B
3              7          95                91          NaN           A
4              3          70                65          4.0           C

In [5]:
df.head(2)

   Hours_Studied  Attendance  Assignment_Score  Sleep_Hours Final_Grade
0              4          80                75          6.0           B
1              6          90                88          7.0           A

In [6]:
a = df.columns
print(a)

Index(['Hours_Studied', 'Attendance', 'Assignment_Score', 'Sleep_Hours',
       'Final_Grade'],
      dtype='object')

In [7]:
type(df.columns)

pandas.core.indexes.base.Index

In [8]:
df.dtypes

Hours_Studied         int64
Attendance            int64
Assignment_Score      int64
Sleep_Hours         float64
Final_Grade          object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Hours_Studied     5 non-null      int64
 1   Attendance        5 non-null      int64
 2   Assignment_Score  5 non-null      int64
 3   Sleep_Hours       4 non-null      float64
 4   Final_Grade       5 non-null      object
dtypes: float64(1), int64(3), object(1)
memory usage: 332.0+ bytes

In [10]:
df.describe()

       Hours_Studied  Attendance  Assignment_Score  Sleep_Hours
count       5.000000    5.000000          5.000000     4.000000
mean        5.000000   84.000000         80.200000     5.500000
std         1.581139    9.617692         10.473777     1.290994
min         3.000000   70.000000         65.000000     4.000000
25%         4.000000   80.000000         75.000000     4.750000
50%         5.000000   85.000000         82.000000     5.500000
75%         6.000000   90.000000         88.000000     6.250000
max         7.000000   95.000000         91.000000     7.000000

In [11]:
df.notnull().sum()

Hours_Studied       5
Attendance          5
Assignment_Score    5
Sleep_Hours         4
Final_Grade         5
dtype: int64

In [18]:
df.head()

   Hours_Studied  Attendance  Assignment_Score  Sleep_Hours Final_Grade
0              4          80                75          6.0           B
1              6          90                88          7.0           A
2              5          85                82          5.0           B
3              7          95                91          5.5           A
4              3          70                65          4.0           C

In [17]:
df['Sleep_Hours'].fillna(df['Sleep_Hours'].mean(), inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_12696\3192260044.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sleep_Hours'].fillna(df['Sleep_Hours'].mean(), inplace=True)

In [19]:
df

   Hours_Studied  Attendance  Assignment_Score  Sleep_Hours Final_Grade
0              4          80                75          6.0           B
1              6          90                88          7.0           A
2              5          85                82          5.0           B
3              7          95                91          5.5           A
4              3          70                65          4.0           C

In [20]:
df['Attendance'].mean()

np.float64(84.0)

In [21]:
df['Final_Grade'].unique()

array(['B', 'A', 'C'], dtype=object)