In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.tree import DecisionTreeRegressor

In [9]:
data = {
    "Experience_Years" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    "Training_Hours" : [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 8, 12, 18, 25, 35, 40, 50, 60, 65, 70],
    "Attendance" : [70, 75, 80, 82, 85, 88, 90, 92, 94, 95, 74, 78, 83, 86, 89, 91, 93, 95, 97, 98]
}

df = pd.DataFrame(data)

In [10]:
df

    Experience_Years  Training_Hours  Attendance
0                  1               5          70
1                  2              10          75
2                  3              15          80
3                  4              20          82
4                  5              25          85
5                  6              30          88
6                  7              35          90
7                  8              40          92
8                  9              45          94
9                 10              50          95
10                 2               8          74
11                 4              12          78
12                 6              18          83
13                 8              25          86
14                10              35          89
15                12              40          91
16                14              50          93
17                16              60          95
18                18              65          97
19                20              70          98

In [8]:
df_copy = df.copy()
df_copy

    Experience_Years  Training_Hours  Attendance
0                  1               5          70
1                  2              10          75
2                  3              15          80
3                  4              20          82
4                  5              25          85
5                  6              30          88
6                  7              35          90
7                  8              40          92
8                  9              45          94
9                 10              50          95
10                 2               8          74
11                 4              12          78
12                 6              18          83
13                 8              25          86
14                10              35          89
15                12              40          91
16                14              50          93
17                16              60          95
18                18              65          97
19                20              70          98

In [11]:
df_copy.describe()

       Experience_Years  Training_Hours  Attendance
count         20.000000       20.000000   20.000000
mean           8.250000       32.900000   86.750000
std            5.447114       19.444658    8.162011
min            1.000000        5.000000   70.000000
25%            4.000000       17.250000   81.500000
50%            7.500000       32.500000   88.500000
75%           10.500000       46.250000   93.250000
max           20.000000       70.000000   98.000000